# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
def nearest_value(arr, val):
    abs_diff = np.abs(arr - val)
    idx = np.argmin(abs_diff)
    return arr[idx]

# Example usage
arr = np.array([1, 4, 7, 9])
val = 5
print(nearest_value(arr, val))  

4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [3]:
# create two arrays with shape (1,3) and (3,1)
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])

# initialize the iterator
it = np.nditer([a, b])

# initialize the sum variable
sum = 0

# iterate over the arrays and compute the sum
for x, y in it:
    sum += x + y

# print the sum
print(sum)


63


#### 63. Create an array class that has a name attribute (★★☆)

In [7]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name='Unnamed'):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

a = NamedArray([1, 2, 3], name='MyArray')
print(a.name)  




MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [9]:
# Example input vectors
v1 = np.array([0, 1, 2, 3, 4])
v2 = np.array([1, 3, 3, 4])

# Get the unique indices from v2
unique_indices = np.unique(v2)

# Add 1 to the elements of v1 corresponding to unique_indices
v1[unique_indices] += 1
print(v1)

[0 2 2 4 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [11]:
# Create the input vector (X), index list (I), and output array (F)
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 2, 1])
F = np.zeros(3)

# Accumulate the elements of X into F based on the indices in I
np.add.at(F, I, X)

# Print the result
print(F)


[1. 7. 7.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [12]:
# Load the image as a numpy array
image = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)

# Reshape the image to a 2D array of shape (w*h, 3)
image_2d = image.reshape((-1, 3))

# Get the unique colors and their counts
unique_colors, counts = np.unique(image_2d, axis=0, return_counts=True)

# Print the number of unique colors
print(f"Number of unique colors: {len(unique_colors)}")


Number of unique colors: 9995


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [13]:
# Create a 4D array with shape (2, 3, 4, 5)
arr = np.random.rand(2, 3, 4, 5)

# Sum over the last two axes
sum_last_two_axes = np.sum(arr, axis=(-2, -1))

print(sum_last_two_axes.shape)  # prints (2, 3, 4)

(2, 3)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [14]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

unique_indices = np.unique(S)  # Get unique subset indices
subset_sizes = np.bincount(S)  # Count elements in each subset

# Compute means of each subset using a list comprehension
subset_means = [np.mean(D[S == i]) for i in unique_indices]

print(subset_means)


[2.0, 5.0, 8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [15]:
# create two arrays
a = np.random.rand(3, 4)
b = np.random.rand(4, 3)

# compute dot product
c = np.einsum('ij,jk->ik', a, b)

# extract diagonal
d = np.diagonal(c)

print(d)

[1.1236485  2.26187132 0.93512837]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [16]:
# Input vector
x = np.array([1, 2, 3, 4, 5])

# Number of zeros to add between each value
n_zeros = 3

# Create an array of zeros
zeros = np.zeros(n_zeros)

# Repeat the input vector and interleave with zeros
y = np.concatenate([np.repeat(x, n_zeros+1)[:-1], zeros])

print(y)

[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 4. 4. 4. 4. 5. 5. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [18]:
# create a 5x5x3 array
a = np.random.rand(5, 5, 3)

# create a 5x5 array
b = np.random.rand(5, 5)

# multiply the two arrays using broadcasting
c = a * b[:, :, np.newaxis]

# c is now a 5x5x3 array, where each element in the last dimension is
# multiplied by the corresponding element in the (5,5) array.
print(c)


[[[3.61464535e-01 2.52112835e-01 4.86563358e-01]
  [1.64544054e-01 1.07075069e-01 1.96157175e-05]
  [5.77768796e-02 1.06577762e-01 1.00250652e-01]
  [7.79306932e-02 7.67187122e-02 1.22695922e-01]
  [2.97608950e-01 1.99127368e-01 1.70309522e-01]]

 [[3.67700756e-01 7.06965400e-01 5.48203426e-01]
  [4.21755433e-01 2.76105764e-01 1.08581200e-01]
  [2.81883470e-01 1.65188496e-01 4.24012952e-01]
  [2.43616843e-01 2.51467671e-01 4.93087622e-02]
  [2.22456861e-01 3.08388893e-01 2.63503348e-01]]

 [[7.86890907e-01 6.54121204e-01 3.93558489e-01]
  [4.31609343e-02 3.99129885e-01 4.49896947e-01]
  [1.40941848e-01 1.97135841e-01 2.01979157e-01]
  [1.80314095e-03 1.72770130e-02 6.41619761e-03]
  [1.25164447e-02 8.18087342e-02 8.51453073e-02]]

 [[2.59527986e-01 5.76692697e-01 7.30841736e-01]
  [3.40388779e-01 1.80081423e-01 4.21703034e-01]
  [6.58659760e-01 5.77688666e-02 4.75420946e-01]
  [3.85394602e-01 5.40019590e-01 7.10449111e-01]
  [2.32518140e-02 1.96288735e-01 4.23618425e-01]]

 [[6.0447396

#### 72. How to swap two rows of an array? (★★★)

In [19]:
# create a 2D array with 3 rows and 4 columns
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# swap rows 0 and 2
temp = arr[0].copy()
arr[0] = arr[2]
arr[2] = temp

print(arr)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [21]:
import numpy as np

# Set of 10 triangles as triplets of vertices
triangles = np.array([
    [(0, 0), (1, 1), (0, 1)],
    [(1, 1), (0, 0), (1, 0)],
    [(0, 0), (1, 0), (1, 1)],
    [(0, 0), (1, 1), (1, 0)],
    [(1, 1), (0, 1), (1, 0)],
    [(0, 0), (0, 1), (1, 1)],
    [(0, 0), (1, 1), (0, 1)],
    [(1, 1), (0, 0), (1, 0)],
    [(0, 0), (1, 0), (1, 1)],
    [(0, 0), (1, 1), (1, 0)]
])

# Compute line segments of each triangle
segments = np.concatenate((triangles[:, :2], triangles[:, 1:], triangles[:, ::2]), axis=0)

# Sort the line segments to find the unique ones
segments.sort(axis=1)
unique_segments = np.unique(segments, axis=0)

print(unique_segments)


[[[0 0]
  [0 1]]

 [[0 0]
  [1 0]]

 [[0 0]
  [1 1]]

 [[0 1]
  [1 1]]

 [[1 0]
  [1 1]]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [26]:
import numpy as np

def sliding_average(arr, window_size):
    # Define the sliding window as an array of ones
    window = np.ones(window_size, dtype=int)
    
    # Convolve the input array with the sliding window
    convolved = np.convolve(arr, window, mode='valid')
    
    # Divide the result by the window size to obtain the averages
    averages = convolved / window_size
    
    return averages


In [23]:
# Example sorted bincount array
C = np.array([0, 1, 2, 3, 0, 2, 1, 0, 1, 2])

# Generate the corresponding array A
A = np.repeat(np.arange(len(C)), C)

# Verify that np.bincount(A) == C
print(np.bincount(A))  
print(np.array_equal(np.bincount(A), C))  



[0 1 2 3 0 2 1 0 1 2]
True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [24]:
def sliding_average(arr, window_size):
    # Define the sliding window as an array of ones
    window = np.ones(window_size, dtype=int)
    
    # Convolve the input array with the sliding window
    convolved = np.convolve(arr, window, mode='valid')
    
    # Divide the result by the window size to obtain the averages
    averages = convolved / window_size
    
    return averages


In [25]:
def sliding_window_average(arr, window_size):
    # Create a sliding window view of the input array
    shape = arr.shape[:-1] + (arr.shape[-1] - window_size + 1, window_size)
    strides = arr.strides + (arr.strides[-1],)
    window_view = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)
    
    # Compute the average of each window
    return np.mean(window_view, axis=-1)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
result = sliding_window_average(arr, window_size)
print(result)


[2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [27]:
def sliding_window(arr, size):
    """Return a sliding window view of the input array."""
    shape = (arr.size - size + 1, size)
    strides = arr.strides * 2
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

# Example usage
Z = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
Z_2d = sliding_window(Z, window_size)
result = Z_2d.T

print(result)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [28]:
#negate a boolean array
a = np.array([True, False, True])
negated_a = ~a
print(negated_a)

[False  True False]


In [29]:
#change the sign of a float array inplace
a = np.array([1.0, -2.0, 3.0])
a *= -1
print(a)  

[-1.  2. -3.]


In [30]:
#create a new array with the negated values
a = np.array([1.0, -2.0, 3.0])
negated_a = np.negative(a)
print(negated_a)

[-1.  2. -3.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [35]:
import numpy as np

def distance_to_lines(P0, P1, p):
    """
    Compute distance from a point to each line segment defined by P0 and P1.
    P0 and P1 have shape (n, 2) and p has shape (2,).
    Returns an array of shape (n,) with the distances.
    """
    # Compute direction of lines
    d = P1 - P0
    
    # Compute denominator
    den = np.linalg.norm(d, axis=1)
    
    # Compute numerator
    num = np.abs(np.cross(d, P0-p, axis=1))
    
    # Compute distances
    dist = num / den
    
    return dist



In [36]:
# Define line segment endpoints
P0 = np.array([[0, 0], [1, 0], [0, 1]])
P1 = np.array([[1, 0], [1, 1], [0, 1]])

# Define point
p = np.array([0.5, 0.5])

# Calculate distances
dist = distance_to_lines(P0, P1, p)

print(dist)


[0.5 0.5 nan]


C:\Users\user\AppData\Local\Temp\ipykernel_11452\3196574999.py:19: RuntimeWarning: invalid value encountered in divide
  dist = num / den


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [37]:
def distance_to_lines(P0, P1, P):
    """
    Compute distance from each point in P to each line segment defined by P0 and P1.
    P0 and P1 have shape (n, 2) and P has shape (m, 2).
    Returns an array of shape (m, n) with the distances.
    """
    # Compute direction of lines
    d = P1 - P0
    
    # Compute denominator
    den = np.linalg.norm(d, axis=1)
    
    # Compute numerator
    v = P - P0[:,np.newaxis]
    num = np.abs(np.cross(d[:,np.newaxis], v, axis=2))
    
    # Compute distances
    dist = num / den[:,np.newaxis]
    
    # Find minimum distance for each point
    min_dist = np.min(dist, axis=0)
    
    return min_dist


In [38]:
# Define lines and points
P0 = np.array([[0,0], [1,0], [1,1]])
P1 = np.array([[1,0], [1,1], [0,1]])
P = np.array([[0.5,0.5], [1,0], [0,0], [1,1]])

# Compute distances
dist = distance_to_lines(P0, P1, P)

print(dist)


[0.5 0.  0.  0. ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [41]:
def extract_subpart(arr, center, shape, fill=0):
    """
    Extract a subpart of the input array with a fixed shape, centered on a given element.
    Pad the subpart with a fill value when necessary.
    """
    # Compute the starting and ending indices of the subpart
    start = np.subtract(center, np.divide(shape, 2)).astype(int)
    end = np.add(start, shape).astype(int)
    
    # Compute the slices to extract the subpart
    slices = tuple(slice(max(0, s), e) for s, e in zip(start, end))
    
    # Initialize a new array with the fill value
    subpart = np.full(shape, fill, dtype=arr.dtype)
    
    # Compute the overlapping region of the subpart and the input array
    overlap_slices = tuple(slice(max(-s, 0), min(e - s, d))
                           for s, e, d in zip(start, end, arr.shape))
    
    # Copy the overlapping region of the input array into the subpart
    subpart[overlap_slices] = arr[slices][overlap_slices]
    
    return subpart


In [42]:
arr = np.arange(25).reshape((5, 5))
center = np.array([2, 2])
shape = np.array([3, 3])

subpart = extract_subpart(arr, center, shape, fill=-1)
print(subpart)


[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [45]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
n = 4  # number of elements per row in R
R = np.lib.stride_tricks.as_strided(Z, shape=(Z.size-n+1, n), strides=(Z.itemsize, Z.itemsize))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [47]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = np.linalg.matrix_rank(A)
print("The rank of matrix A is:", rank)


The rank of matrix A is: 2


#### 83. How to find the most frequent value in an array?

In [48]:
# Create an example array
arr = np.array([1, 2, 3, 4, 2, 3, 2, 1, 2, 3, 3])

# Compute the bin counts
counts = np.bincount(arr)

# Find the index of the maximum count
most_frequent_value = np.argmax(counts)

# Print the result
print("The most frequent value is:", most_frequent_value)


The most frequent value is: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
# Generate a random 10x10 matrix
matrix = np.random.rand(10, 10)

# Extract all the contiguous 3x3 blocks
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides * 2)

# Print the result
print(blocks)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [54]:
import numpy as np
#create a new SymmetricArray and enforce the symmetry property.
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __setitem__(self, key, value):
        i, j = key
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

#create a SymmetricArray object from a regular 2D numpy array 
a = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
sa = SymmetricArray(a)

#access and set elements in the SymmetricArray object
print(sa[1, 2])  # 5
print(sa[2, 1])  # 5

sa[0, 2] = 4
print(sa)


5
5
[[1 2 4]
 [2 4 5]
 [4 5 6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [58]:
# Define matrices and vectors
A = np.array([[1, 2], [3, 4]])
B = np.array([[5], [6]])
C = np.array([[7, 8], [9, 10]])

# Check dimensions
print(A.shape, B.shape, C.shape)

# Compute sum of matrix products
result = A @ B + C @ B

# Print result
print(result)


(2, 2) (2, 1) (2, 2)
[[100]
 [144]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [59]:
# Create a 16x16 array
arr = np.arange(256).reshape((16,16))

# Reshape the array into a 4D array of blocks
blocks = arr.reshape((4,4,4,4))

# Compute the block-sum by summing over the last two dimensions
block_sum = np.sum(blocks, axis=(2,3))

print(block_sum)


[[ 120  376  632  888]
 [1144 1400 1656 1912]
 [2168 2424 2680 2936]
 [3192 3448 3704 3960]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def compute_next_generation(grid):
    # Compute the number of live neighbors for each cell
    neighbors_count = np.zeros_like(grid)
    neighbors_count[1:,1:] += grid[:-1,:-1]
    neighbors_count[1:,:] += grid[:-1,:]
    neighbors_count[1:,:-1] += grid[:-1,1:]
    neighbors_count[:-1,1:] += grid[1:,:-1]
    neighbors_count[:-1,:] += grid[1:,:]
    neighbors_count[:-1,:-1] += grid[1:,1:]
    
    # Compute the next state of each cell based on the number of live neighbors
    next_grid = np.zeros_like(grid)
    next_grid[np.logical_and(grid == 1, neighbors_count >= 2)] = 1
    next_grid[np.logical_and(grid == 1, neighbors_count <= 3)] = 1
    next_grid[np.logical_and(grid == 0, neighbors_count == 3)] = 1
    
    return next_grid

# Define the initial state of the grid
grid = np.zeros((20, 20))
grid[5:8, 5:8] = np.array([[0, 1, 0], [0, 0, 1], [1, 1, 1]])

# Simulate the game for 100 steps
for i in range(100):
    print(grid)
    grid = compute_next_generation(grid)


#### 89. How to get the n largest values of an array (★★★)

In [61]:
arr = np.array([1, 3, 2, 4, 5, 7, 6, 8, 9, 10])

n = 3 # get 3 largest values

largest_n_values = np.partition(arr, -n)[-n:]

print(largest_n_values)


[ 8  9 10]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [62]:
import itertools

vectors = [[1, 2, 3], [4, 5], [6, 7, 8]]
cartesian_product = list(itertools.product(*vectors))

print(cartesian_product)


[(1, 4, 6), (1, 4, 7), (1, 4, 8), (1, 5, 6), (1, 5, 7), (1, 5, 8), (2, 4, 6), (2, 4, 7), (2, 4, 8), (2, 5, 6), (2, 5, 7), (2, 5, 8), (3, 4, 6), (3, 4, 7), (3, 4, 8), (3, 5, 6), (3, 5, 7), (3, 5, 8)]


#### 91. How to create a record array from a regular array? (★★★)

In [63]:
# Create a regular NumPy array
data = np.array([(1, 2, 3), (4, 5, 6)], dtype=np.int32)

# Define the record datatype with fields
dt = np.dtype([('field1', 'i4'), ('field2', 'i4'), ('field3', 'i4')])

# Create a record array from the regular array
record_array = np.rec.array(data, dtype=dt)

# Print the record array
print(record_array)


[[(1, 2, 3)]
 [(4, 5, 6)]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [64]:
#Using the np.power() function:
Z_cube = np.power(Z, 3)

#Using the * operator to perform element-wise multiplication:
Z_cubed = Z * Z * Z


#Using the numpy.dot() function to perform matrix multiplication:
Z_cubed = np.dot(np.dot(Z, Z), Z)



In [66]:
# Create a large vector
Z = np.random.rand(1000000)

# Method 1
def method1(Z):
    return Z*Z*Z

Z_power_3 = method1(Z)
print(f"Method 1 result: {Z_power_3[:10]}")

# Method 2
def method2(Z):
    return np.power(Z, 3)

Z_power_3 = method2(Z)
print(f"Method 2 result: {Z_power_3[:10]}")

# Method 3
def method3(Z):
    return np.multiply(np.multiply(Z, Z), Z)

Z_power_3 = method3(Z)
print(f"Method 3 result: {Z_power_3[:10]}")


Method 1 result: [5.21196687e-03 6.26587564e-01 5.39773321e-01 2.03117898e-01
 5.94206736e-02 2.37692457e-01 3.75731086e-02 9.73648673e-03
 2.32048593e-04 3.44226914e-01]
Method 2 result: [5.21196687e-03 6.26587564e-01 5.39773321e-01 2.03117898e-01
 5.94206736e-02 2.37692457e-01 3.75731086e-02 9.73648673e-03
 2.32048593e-04 3.44226914e-01]
Method 3 result: [5.21196687e-03 6.26587564e-01 5.39773321e-01 2.03117898e-01
 5.94206736e-02 2.37692457e-01 3.75731086e-02 9.73648673e-03
 2.32048593e-04 3.44226914e-01]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [67]:
# Sample data
A = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6],
              [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10]])
B = np.array([[3, 2], [7, 6]])

# Create sets of rows for each array
set_A = [set(row) for row in A]
set_B = [set(row) for row in B]

# Find the intersection of the sets of each row of B with the sets of each row of A
intersections = [set_A[i] & set_B[j] for i in range(A.shape[0]) for j in range(B.shape[0])]

# Find the rows of A that have non-empty intersection with all rows of B
result = np.array([i for i, intersection in enumerate(intersections) if len(intersection) == B.shape[1]])

print(result)


[ 0  2  9 11]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [68]:
# create a random 10x3 matrix
mat = np.random.randint(0, 3, size=(10, 3))

# create a boolean mask indicating which rows have at least one element
# different from the first element of the row
mask = ~np.all(mat == mat[:, None, 0], axis=-1)

# extract the rows with unequal values
unequal_rows = mat[mask]

print("Original matrix:\n", mat)
print("Rows with unequal values:\n", unequal_rows)


Original matrix:
 [[2 2 1]
 [2 0 1]
 [1 1 0]
 [2 0 0]
 [0 0 2]
 [1 2 2]
 [2 1 1]
 [1 2 0]
 [1 2 0]
 [2 2 2]]
Rows with unequal values:
 [[2 2 1]
 [2 0 1]
 [1 1 0]
 [2 0 0]
 [0 0 2]
 [1 2 2]
 [2 1 1]
 [1 2 0]
 [1 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [69]:
def int_to_binary_matrix(vector):
    # Convert each integer to 8-bit binary representation
    binary = np.unpackbits(np.uint8(vector[:, np.newaxis]), axis=1)

    # Reshape the binary matrix to have the same number of rows as the original vector
    num_rows = vector.shape[0]
    binary_matrix = np.reshape(binary, (num_rows, -1))

    return binary_matrix


In [70]:
# Example input vector
v = np.array([1, 2, 3, 4, 5])

# Convert vector to binary matrix
binary_matrix = int_to_binary_matrix(v)

# Output the binary matrix
print(binary_matrix)


[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [71]:
# create a 2D array with some duplicate rows
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])

# use numpy.unique to extract unique rows
unique_rows = np.unique(arr, axis=0)

# print the result
print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [73]:
# inner product
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_product = np.einsum('i,i->', A, B)

# outer product
outer_product = np.einsum('i,j->ij', A, B)

# sum
sum_AB = np.einsum('i->', A)

# elementwise multiplication
mul_AB = np.einsum('i,i->i', A, B)

print(inner_product)
print(outer_product)
print(sum_AB)
print(mul_AB)

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
6
[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [74]:
# Define the path (X,Y)
X = np.array([0, 1, 3, 4, 6, 7, 8, 10])
Y = np.array([0, 2, 3, 4, 3, 2, 1, 0])

# Calculate the total length of the path
path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
path_length = np.insert(path_length, 0, 0)

# Define the number of equidistant samples to take
num_samples = 20

# Generate equidistant samples along the path
sample_points = np.linspace(0, path_length[-1], num_samples)
sampled_X = np.interp(sample_points, path_length, X)
sampled_Y = np.interp(sample_points, path_length, Y)

# Print the sampled X and Y values
print("Sampled X values:", sampled_X)
print("Sampled Y values:", sampled_Y)


Sampled X values: [ 0.          0.31038772  0.62077543  0.93116315  1.48310172  2.10387716
  2.72465259  3.27308483  3.7638509   4.32206782  4.94284325  5.56361868
  6.14577634  6.63654241  7.12730848  7.61807455  8.13767371  8.75844914
  9.37922457 10.        ]
Sampled Y values: [0.         0.62077543 1.24155086 1.86232629 2.24155086 2.55193858
 2.86232629 3.27308483 3.7638509  3.83896609 3.52857838 3.21819066
 2.85422366 2.36345759 1.87269152 1.38192545 0.93116315 0.62077543
 0.31038772 0.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [78]:
import numpy as np

def multinomial_rows(n, X):
    is_int = np.equal(np.mod(X, 1), 0)  # check if all elements are integers
    sums = np.sum(X, axis=1)  # compute row sums
    is_n = np.equal(sums.reshape(-1, 1), n)  # check if row sums are equal to n
    is_multinomial = np.logical_and(is_int, is_n)  # combine the two conditions
    return X[is_multinomial]


In [79]:
X = np.array([[1, 2, 2], [0, 5, 2], [2, 2, 1], [3, 1, 1], [0, 0, 5]])
n = 5
result = multinomial_rows(n, X)
print(result)


[1 2 2 2 2 1 3 1 1 0 0 5]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [80]:
import numpy as np

def bootstrap_mean_ci(X, N=1000, alpha=0.05):
    """
    Compute bootstrapped 95% confidence intervals for the mean of an array X.
    
    Parameters:
    -----------
    X : ndarray
        The input 1D array.
    N : int, optional (default=1000)
        The number of resamples to use for bootstrapping.
    alpha : float, optional (default=0.05)
        The significance level (i.e., Type I error rate) for the confidence intervals.
    
    Returns:
    --------
    mean_ci : tuple of floats
        The lower and upper bounds of the bootstrapped 95% confidence intervals for the mean of X.
    """
    # Initialize an empty array to hold the bootstrap sample means
    sample_means = np.empty(N)
    
    # Generate N bootstrap samples and compute their means
    for i in range(N):
        sample = np.random.choice(X, size=len(X), replace=True)
        sample_means[i] = np.mean(sample)
    
    # Compute the percentile-based confidence intervals
    lower_ci = np.percentile(sample_means, 100 * alpha / 2)
    upper_ci = np.percentile(sample_means, 100 * (1 - alpha / 2))
    
    return lower_ci, upper_ci


In [81]:
# Generate an example array X
X = np.random.normal(loc=0, scale=1, size=100)

# Compute the bootstrapped 95% confidence intervals for the mean of X
lower_ci, upper_ci = bootstrap_mean_ci(X, N=1000, alpha=0.05)

# Print the confidence intervals
print(f"Bootstrapped 95% confidence intervals for the mean of X: ({lower_ci:.3f}, {upper_ci:.3f})")


Bootstrapped 95% confidence intervals for the mean of X: (-0.431, 0.000)
